#!/bin/bash

# Function to display usage
display_help() {
    echo "Usage: zgit up"
    echo ""
    echo "Switches to the first sibling branch found in the list generated by 'git branch'."
}

# Main function to handle the branch switch
main() {
    # Get the current branch name
    local current_branch=$(git rev-parse --abbrev-ref HEAD)

    # Extract the common prefix from the current branch name
    local common_prefix=$(echo "$current_branch" | grep -o '^[^-]*-[^-]*')

    # Get a list of sibling branches
    local sibling_branches=$(git branch | grep "$common_prefix" | grep -v "$current_branch" | sed 's/^[* ] //')

    # Get the first sibling branch from the list
    local first_sibling=$(echo "$sibling_branches" | head -n 1)

    if [[ -n "$first_sibling" ]]; then
        # Checkout the first sibling branch
        git checkout "$first_sibling"
    else
        echo "No sibling branches found."
        exit 1
    fi
}

# If the script is called with a function name, execute that function
if [[ -n $1 ]] && declare -F "$1" > /dev/null; then
    "$@"
else
    # If no function name is provided, or if the function doesn't exist, call main by default
    main "$@"
fi
