#!/bin/bash

source "$(dirname "$0")/helpers/get_parents.sh"

# Function to display usage
display_help() {
    echo "Usage: zgit up"
    echo ""
    echo "Switches to the first sibling branch found in the list generated by 'git branch'."
}

# Main function to handle the branch switch
main() {
    # Get the current branch name
    local current_branch=$(git rev-parse --abbrev-ref HEAD)

    local first_parent=$(get_parent "$current_branch")

    if [[ -n "$first_parent" ]]; then
        # Checkout the first sibling branch
        git checkout "$first_parent"
    else
        echo "No sibling branches found."
        exit 1
    fi
}

# If the script is called with a function name, execute that function
if [[ -n $1 ]] && declare -F "$1" > /dev/null; then
    "$@"
else
    # If no function name is provided, or if the function doesn't exist, call main by default
    main "$@"
fi
